---

- hosts: localhost
  connection: local
  tasks:
    - name: Remove existing unofficial Docker packages
      dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-common
        - container-selinux
        - docker-selinux
    - name: Install dnf-plugins-core to manage DNF repository
      dnf:
        name:  dnf-plugins-core
        state: present
    - name: Add docker repo
      shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    - name: Install docker-ce
      dnf:
        name: docker-ce
        state: latest
    - name: Install IntelliJ Idea with snap
      snap:
        name: intellij-idea-community 
        classic: yes
        state: present
